#!/usr/bin/env python3
"""
The vendored design system: intact, and the only source of style here.

`trafficdom_design.py` is generated by the Growth Engine and copied in. It is
what makes the Analytics report and the Growth report look like one suite
without either repository importing the other — which would invert the
relationship the whole architecture rests on (the Growth Engine consumes this
repository's published contract, not the other way round).

A vendored file has exactly one failure mode worth guarding: somebody edits it
here, the two reports drift, and nothing says so until a client notices the
pages no longer match. So:

* the file declares the fingerprint it was generated at, and this test recomputes
  it from the content — a hand-edit fails here;
* the dashboard is checked for style of its own, because a `<style>` block or a
  hard-coded colour in the report would defeat the shared system just as
  effectively as editing the vendored copy.

To change how reports look, change the design system in the Growth Engine and
re-export:

    python3 -m growth_engine design --export \\
        automations/analytics/trafficdom_design.py

Run with:  python3 -m pytest automations/analytics/
"""

import ast
import hashlib
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import dashboard as dash  # noqa: E402
import trafficdom_design as td  # noqa: E402

VENDORED = Path(td.__file__)


def test_the_vendored_copy_has_not_been_edited():
    """Verified against the file's own integrity hash.

    The check needs to know nothing about how the file was assembled — a check
    that reconstructs the exporter's internals drifts from them, which is the
    failure it exists to catch.
    """
    source = VENDORED.read_text(encoding="utf-8")
    marker = "# --- integrity ---"
    assert marker in source, "the vendored file carries no integrity marker"

    above, below = source.split(marker, 1)
    declared = re.search(r'CONTENT_HASH = "([0-9a-f]+)"', below).group(1)
    recomputed = hashlib.sha256(above.encode("utf-8")).hexdigest()[:16]

    assert recomputed == declared, (
        "trafficdom_design.py has been edited in this repository. Don't — the "
        "two reports would drift silently. Change the design in the Growth "
        "Engine and re-export."
    )
    assert td.CONTENT_HASH == declared


def test_it_declares_where_it_came_from_and_how_to_change_it():
    source = VENDORED.read_text(encoding="utf-8")
    assert "VENDORED, DO NOT EDIT" in source
    assert "growth_engine design --export" in source


def test_it_imports_nothing_but_the_standard_library():
    """It has to render on a runner with only this repository installed."""
    tree = ast.parse(VENDORED.read_text(encoding="utf-8"))
    imported = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported += [alias.name for alias in node.names]
        elif isinstance(node, ast.ImportFrom):
            assert node.level == 0, "a relative import survived the export"
            imported.append(node.module or "")
    assert imported
    for name in imported:
        assert name.split(".")[0] in {"html", "dataclasses"}, name


def test_the_dashboard_writes_no_style_of_its_own():
    """A <style> block here would defeat the shared system as surely as an edit."""
    source = Path(dash.__file__).read_text(encoding="utf-8")
    tree = ast.parse(source)
    docstrings = set()
    for node in ast.walk(tree):
        # Only these carry a LIST body; `IfExp.body` is a single expression and
        # subscripting it would crash this guard rather than fail it.
        if not isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef,
                                 ast.AsyncFunctionDef)):
            continue
        body = node.body or []
        first = body[0] if body else None
        if (isinstance(first, ast.Expr)
                and isinstance(first.value, ast.Constant)
                and isinstance(first.value.value, str)):
            docstrings.add(id(first.value))

    for node in ast.walk(tree):
        if (isinstance(node, ast.Constant) and isinstance(node.value, str)
                and id(node) not in docstrings):
            for marker in ("<style", "<div", "<span", "<article", "<table",
                           "#f", "px;", "rem;"):
                assert marker not in node.value, (
                    f"{node.value[:60]!r} looks like markup or style; it "
                    "belongs in the design system, not in this report."
                )


def test_both_reports_use_the_same_component_vocabulary():
    """The suite is the components, not a shared colour."""
    for component in ("page", "wrap", "report_header", "conclusion_card",
                      "metric", "metric_band", "section", "priority_row",
                      "priority_list", "data_table", "sparkline", "note_panel",
                      "status_chip", "technical_drawer", "technical_table",
                      "empty_state", "footer"):
        assert callable(getattr(td, component, None)), component


def test_the_rendered_page_carries_the_shared_class_names():
    page = dash.render_dashboard(dash.document_from_fixture("healthy"))
    for marker in ("td-wrap", "td-header", "td-conclusion", "td-metrics",
                   "td-section", "td-priority", "td-technical", "td-footer"):
        assert marker in page, marker
    # And none of the report's own former styling survives.
    for gone in ("ms-metric", "ms-section", "ms-rec", "ms-table", "ms-foot"):
        assert gone not in page, gone
